server:
  port: 8082

security:
  oauth2:
    resource:
      token-info-uri: http://auth-server:8080/oauth/check_token
      user-info-uri: http://auth-server:8080/oauth/user
    client:
      client-id: santhosh
      client-secret: santhosh
spring:
  application:
    name: Protected Resource
  data:
    mongodb:
      host: db
      port: 27017
      database: products
  zipkin:
    enabled: false
